import mailgen from 'mailgen'
import 'dotenv/config'
import nodemailer from 'nodemailer'
import { moduleLogger } from '@sliit-foss/module-logger'

const logger = moduleLogger('Admin-Email-Service')

const mailTransporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_TOKEN,
  },
  secure: false,
  tls: {
    rejectUnauthorized: false,
  },
})

const sendGeneratedPassord = async (adminObj, autoGeneratedPassword) => {
  const MailGenerator = new mailgen({
    theme: 'cerberus',
    product: {
      name: 'FixACareer',
      link: 'http://localhost:5173/',
      logo: 'https://drive.google.com/file/d/1L5LeUn4dhoYdNIJLoY5uHnPFONAXcvwF/view',
    },
  })

  const email = {
    body: {
      name: `${adminObj.firstName} ${adminObj.lastName}`,
      intro: `You have been added as an administartor to FixACareer System. We have generated a temporary password for you to access your admin profile.`,
      action: {
        instructions: `Your temporary password is:<br><h1>${autoGeneratedPassword}</h1>`,
        button: {
          color: '#22BC66',
          text: 'Go to Admin Dashboard',
          link: 'http://localhost:5173/admin/login/',
        },
      },
      outro: 'To ensure security, we advise you to change your password when you first log in. If you have any queries or concerns, please feel free to contact our support team.',
    },
  }

  // convert mailgen body into HTML
  const mail = MailGenerator.generate(email)

  // nodemailer sending credentials
  const details = {
    from: process.env.EMAIL_USER,
    to: `${adminObj.email}`,
    subject: `You are registered in to FixACareer`,
    html: mail,
  }

  // send mail through nodemailer
  await mailTransporter
    .sendMail(details)
    .then(() => {
      logger.info(`Email sent to ${adminObj.email}`)
    })
    .catch((error) => {
      logger.error(`An error occurred when sending email - err: ${error.message}`)
    })
}

const sendOTP = async (adminObj, otp) => {
  const MailGenerator = new mailgen({
    theme: 'cerberus',
    product: {
      name: 'FixACareer',
      link: 'http://localhost:5173/',
      logo: 'https://drive.google.com/file/d/1L5LeUn4dhoYdNIJLoY5uHnPFONAXcvwF/view',
    },
  })

  const email = {
    body: {
      name: `${adminObj.firstName} ${adminObj.lastName}`,
      intro: `You have requested to login to FixACareer. Please use the following OTP to login to your account.`,
      action: {
        instructions: `Your OTP is:<br><h1>${otp}</h1>`,
        button: {
          color: '#22BC66',
          text: 'Go to Admin Dashboard',
          link: 'http://localhost:5173/admin/login/',
        },
      },
      outro: 'If you have any queries or concerns, please feel free to contact our support team.',
    },
  }

  // convert mailgen body into HTML
  const mail = MailGenerator.generate(email)

  // nodemailer sending credentials
  const details = {
    from: process.env.EMAIL_USER,
    to: `${adminObj.email}`,
    subject: `Your OTP to login to FixACareer Admin Dashboard`,
    html: mail,
  }

  // send mail through nodemailer
  await mailTransporter
    .sendMail(details)
    .then(() => {
      logger.info(`Email sent to ${adminObj.email}`)
    })
    .catch((error) => {
      logger.error(`An error occurred when sending email - err: ${error.message}`)
    })
}

const senPasswordResetEmail = async (adminObj, newPassword) => {
  const MailGenerator = new mailgen({
    theme: 'cerberus',
    product: {
      name: 'FixACareer',
      link: '#',
      logo: 'https://drive.google.com/file/d/1L5LeUn4dhoYdNIJLoY5uHnPFONAXcvwF/view',
    },
  })

  const email = {
    body: {
      name: `${adminObj.firstName} ${adminObj.lastName}`,
      intro: `You have requested to reset your password. We have generated a temporary password for you to access.`,
      action: {
        instructions: `Your temporary password is:<br><h1>${newPassword}</h1>`,
        button: {
          color: '#22BC66',
          text: 'Go to Admin Dashboard',
          link: '#',
        },
      },
      outro: 'To ensure security, we advise you to change your password when you first log in. If you have any queries or concerns, please feel free to contact our support team.',
    },
  }

  // convert mailgen body into HTML
  const mail = MailGenerator.generate(email)

  // nodemailer sending credentials
  const details = {
    from: process.env.EMAIL_USER,
    to: `${adminObj.email}`,
    subject: `Your password has been reset`,
    html: mail,
  }

  // send mail through nodemailer
  await mailTransporter
    .sendMail(details)
    .then(() => {
      logger.info(`Email sent to ${adminObj.email}`)
    })
    .catch((error) => {
      logger.error(`An error occurred when sending email - err: ${error.message}`)
    })
}

const AdminEmailService = {
  sendGeneratedPassord,
  sendOTP,
  senPasswordResetEmail,
}

export default AdminEmailService
